prompt PL/SQL Developer import file
prompt Created on 2014年3月11日 by kenny
set feedback off
set define off
prompt Dropping CONTROL_LOGGER...
drop table CONTROL_LOGGER cascade constraints;
prompt Dropping CONTROL_TASK...
drop table CONTROL_TASK cascade constraints;
prompt Dropping CTL_TABLE_LOG...
drop table CTL_TABLE_LOG cascade constraints;
prompt Dropping DATACALENDAR...
drop table DATACALENDAR cascade constraints;
prompt Dropping DATACALENDARYEAR...
drop table DATACALENDARYEAR cascade constraints;
prompt Dropping D_ETLDATE...
drop table D_ETLDATE cascade constraints;
prompt Dropping ETL_DATA_SYSTEM...
drop table ETL_DATA_SYSTEM cascade constraints;
prompt Dropping ETL_EVENT...
drop table ETL_EVENT cascade constraints;
prompt Dropping ETL_GROUPMEMBER...
drop table ETL_GROUPMEMBER cascade constraints;
prompt Dropping ETL_IGN_BYPASS_JOBS...
drop table ETL_IGN_BYPASS_JOBS cascade constraints;
prompt Dropping ETL_JOB...
drop table ETL_JOB cascade constraints;
prompt Dropping ETL_JOB_DEPENDENCY...
drop table ETL_JOB_DEPENDENCY cascade constraints;
prompt Dropping ETL_JOB_GROUP...
drop table ETL_JOB_GROUP cascade constraints;
prompt Dropping ETL_JOB_GROUPCHILD...
drop table ETL_JOB_GROUPCHILD cascade constraints;
prompt Dropping ETL_JOB_INI...
drop table ETL_JOB_INI cascade constraints;
prompt Dropping ETL_JOB_LOG...
drop table ETL_JOB_LOG cascade constraints;
prompt Dropping ETL_JOB_QUEUE...
drop table ETL_JOB_QUEUE cascade constraints;
prompt Dropping ETL_JOB_SOURCE...
drop table ETL_JOB_SOURCE cascade constraints;
prompt Dropping ETL_JOB_STATUS...
drop table ETL_JOB_STATUS cascade constraints;
prompt Dropping ETL_JOB_STREAM...
drop table ETL_JOB_STREAM cascade constraints;
prompt Dropping ETL_JOB_TIMEWINDOW...
drop table ETL_JOB_TIMEWINDOW cascade constraints;
prompt Dropping ETL_JOB_TRACE...
drop table ETL_JOB_TRACE cascade constraints;
prompt Dropping ETL_NOTIFICATION...
drop table ETL_NOTIFICATION cascade constraints;
prompt Dropping ETL_RECEIVED_FILE...
drop table ETL_RECEIVED_FILE cascade constraints;
prompt Dropping ETL_RECORD_LOG...
drop table ETL_RECORD_LOG cascade constraints;
prompt Dropping ETL_RELATEDJOB...
drop table ETL_RELATEDJOB cascade constraints;
prompt Dropping ETL_SERVER...
drop table ETL_SERVER cascade constraints;
prompt Dropping ETL_SYS...
drop table ETL_SYS cascade constraints;
prompt Dropping ETL_TABLE...
drop table ETL_TABLE cascade constraints;
prompt Dropping ETL_TIMETRIGGER...
drop table ETL_TIMETRIGGER cascade constraints;
prompt Dropping ETL_TIMETRIGGER_CALENDAR...
drop table ETL_TIMETRIGGER_CALENDAR cascade constraints;
prompt Dropping ETL_TIMETRIGGER_MONTHLY...
drop table ETL_TIMETRIGGER_MONTHLY cascade constraints;
prompt Dropping ETL_TIMETRIGGER_WEEKLY...
drop table ETL_TIMETRIGGER_WEEKLY cascade constraints;
prompt Dropping ETL_UNLOAD_PRO...
drop table ETL_UNLOAD_PRO cascade constraints;
prompt Dropping ETL_USER...
drop table ETL_USER cascade constraints;
prompt Dropping ETL_USERGROUP...
drop table ETL_USERGROUP cascade constraints;
prompt Dropping T_COL_ROW...
drop table T_COL_ROW cascade constraints;
prompt Creating CONTROL_LOGGER...
create table CONTROL_LOGGER
(
  TASK_NAME VARCHAR2(50),
  SYS_NAME  VARCHAR2(50),
  STARTDATE VARCHAR2(50),
  ENDDATE   VARCHAR2(50),
  MSG       VARCHAR2(225),
  ETLDATE   VARCHAR2(50),
  STATUS    INTEGER
)
;

prompt Creating CONTROL_TASK...
create table CONTROL_TASK
(
  TASK_NAME VARCHAR2(50),
  SYS_NAME  VARCHAR2(50),
  SRC_TABLE VARCHAR2(50),
  TGT_TABLE VARCHAR2(50),
  TABLE_CN  VARCHAR2(100),
  FILE_NAME VARCHAR2(50),
  STATUS    INTEGER
)
;

prompt Creating CTL_TABLE_LOG...
create table CTL_TABLE_LOG
(
  SYSNAME     VARCHAR2(3),
  TABLENAME   VARCHAR2(30),
  DATAFILE    VARCHAR2(30),
  LOGNAME     VARCHAR2(30),
  BISDATE     VARCHAR2(8),
  DESCRIPTION VARCHAR2(50)
)
;

prompt Creating DATACALENDAR...
create table DATACALENDAR
(
  ETL_SYSTEM    CHAR(3) not null,
  ETL_JOB       VARCHAR2(50) not null,
  CALENDARYEAR  NUMBER(38) not null,
  SEQNUM        NUMBER(38) not null,
  CALENDARMONTH NUMBER(38) not null,
  CALENDARDAY   NUMBER(38) not null,
  CHECKFLAG     CHAR(1)
)
;

prompt Creating DATACALENDARYEAR...
create table DATACALENDARYEAR
(
  ETL_SYSTEM   CHAR(3) not null,
  ETL_JOB      VARCHAR2(50) not null,
  CALENDARYEAR NUMBER(38) not null
)
;

prompt Creating D_ETLDATE...
create table D_ETLDATE
(
  ETLDATE   VARCHAR2(10),
  STARTDATE VARCHAR2(10),
  ENDDATE   VARCHAR2(10),
  SYS_TYPE  VARCHAR2(10),
  STATUS    INTEGER
)
;

prompt Creating ETL_DATA_SYSTEM...
create table ETL_DATA_SYSTEM
(
  ETL_DATA_SYSTEM VARCHAR2(50) not null,
  ETL_SYSTEM      VARCHAR2(3),
  ETL_SERVER      VARCHAR2(10)
)
;

prompt Creating ETL_EVENT...
create table ETL_EVENT
(
  EVENTID     VARCHAR2(20) not null,
  EVENTSTATUS CHAR(1) not null,
  SEVERITY    CHAR(1) not null,
  DESCRIPTION VARCHAR2(200),
  LOGTIME     CHAR(19) not null,
  CLOSETIME   CHAR(19)
)
;

prompt Creating ETL_GROUPMEMBER...
create table ETL_GROUPMEMBER
(
  USERNAME  VARCHAR2(15) not null,
  GROUPNAME VARCHAR2(15) not null
)
;

prompt Creating ETL_IGN_BYPASS_JOBS...
create table ETL_IGN_BYPASS_JOBS
(
  ETL_SYSTEM CHAR(3) not null,
  ETL_JOB    VARCHAR2(50) not null
)
;

prompt Creating ETL_JOB...
create table ETL_JOB
(
  ETL_SYSTEM      CHAR(3) not null,
  ETL_JOB         VARCHAR2(50) not null,
  ETL_SERVER      VARCHAR2(10),
  DESCRIPTION     VARCHAR2(50),
  FREQUENCY       VARCHAR2(30),
  JOBTYPE         CHAR(1),
  ENABLE          CHAR(1),
  LAST_STARTTIME  CHAR(19),
  LAST_ENDTIME    CHAR(19),
  LAST_JOBSTATUS  VARCHAR2(20),
  LAST_TXDATE     DATE,
  LAST_FILECNT    NUMBER(38),
  LAST_CUBESTATUS CHAR(20),
  CUBEFLAG        CHAR(1),
  CHECKFLAG       CHAR(1),
  AUTOOFF         CHAR(1),
  CHECKCALENDAR   CHAR(1),
  CALENDARBU      VARCHAR2(15),
  RUNNINGSCRIPT   VARCHAR2(50),
  JOBSESSIONID    NUMBER(38),
  EXPECTEDRECORD  NUMBER(38),
  CHECKLASTSTATUS CHAR(1),
  TIMETRIGGER     CHAR(1),
  JOB_PRIORITY    NUMBER(38)
)
;

prompt Creating ETL_JOB_DEPENDENCY...
create table ETL_JOB_DEPENDENCY
(
  ETL_SYSTEM        CHAR(3) not null,
  ETL_JOB           VARCHAR2(50) not null,
  DEPENDENCY_SYSTEM CHAR(3) not null,
  DEPENDENCY_JOB    VARCHAR2(50) not null,
  DESCRIPTION       VARCHAR2(50),
  ENABLE            CHAR(1)
)
;

prompt Creating ETL_JOB_GROUP...
create table ETL_JOB_GROUP
(
  GROUPNAME   VARCHAR2(50) not null,
  DESCRIPTION VARCHAR2(50),
  ETL_SYSTEM  CHAR(3),
  ETL_JOB     VARCHAR2(50),
  AUTOONCHILD CHAR(1)
)
;

prompt Creating ETL_JOB_GROUPCHILD...
create table ETL_JOB_GROUPCHILD
(
  GROUPNAME   VARCHAR2(50) not null,
  ETL_SYSTEM  CHAR(3) not null,
  ETL_JOB     VARCHAR2(50) not null,
  DESCRIPTION VARCHAR2(50),
  ENABLE      CHAR(1),
  CHECKFLAG   CHAR(1),
  TXDATE      CHAR(10),
  TURNONFLAG  CHAR(1)
)
;

prompt Creating ETL_JOB_INI...
create table ETL_JOB_INI
(
  ETL_JOB VARCHAR2(50) not null
)
;

prompt Creating ETL_JOB_LOG...
create table ETL_JOB_LOG
(
  ETL_SYSTEM   CHAR(3) not null,
  ETL_JOB      VARCHAR2(50) not null,
  JOBSESSIONID NUMBER(38) not null,
  SCRIPTFILE   VARCHAR2(60) not null,
  TXDATE       DATE not null,
  STARTTIME    CHAR(19),
  ENDTIME      CHAR(19),
  RETURNCODE   NUMBER(38),
  SECONDS      NUMBER(38)
)
;

prompt Creating ETL_JOB_QUEUE...
create table ETL_JOB_QUEUE
(
  ETL_SERVER  VARCHAR2(10) not null,
  SEQID       NUMBER(38) not null,
  ETL_SYSTEM  CHAR(3) not null,
  ETL_JOB     VARCHAR2(50) not null,
  TXDATE      DATE,
  REQUESTTIME VARCHAR2(19)
)
;

prompt Creating ETL_JOB_SOURCE...
create table ETL_JOB_SOURCE
(
  SOURCE         VARCHAR2(36) not null,
  ETL_SYSTEM     CHAR(3) not null,
  ETL_JOB        VARCHAR2(50) not null,
  CONV_FILE_HEAD VARCHAR2(50) not null,
  AUTOFILTER     CHAR(1),
  ALERT          CHAR(1),
  BEFOREHOUR     NUMBER(38),
  BEFOREMIN      NUMBER(38),
  OFFSETDAY      NUMBER(38),
  LASTCOUNT      NUMBER(38)
)
;

prompt Creating ETL_JOB_STATUS...
create table ETL_JOB_STATUS
(
  ETL_SYSTEM     CHAR(3) not null,
  ETL_JOB        VARCHAR2(50) not null,
  JOBSESSIONID   NUMBER(38) not null,
  TXDATE         DATE not null,
  STARTTIME      CHAR(19),
  ENDTIME        CHAR(19),
  JOBSTATUS      VARCHAR2(20),
  FILECNT        NUMBER(38),
  CUBESTATUS     VARCHAR2(20),
  EXPECTEDRECORD NUMBER(38)
)
;

prompt Creating ETL_JOB_STREAM...
create table ETL_JOB_STREAM
(
  ETL_SYSTEM    CHAR(3) not null,
  ETL_JOB       VARCHAR2(50) not null,
  STREAM_SYSTEM CHAR(3) not null,
  STREAM_JOB    VARCHAR2(50) not null,
  DESCRIPTION   VARCHAR2(50),
  ENABLE        CHAR(1)
)
;

prompt Creating ETL_JOB_TIMEWINDOW...
create table ETL_JOB_TIMEWINDOW
(
  ETL_SYSTEM CHAR(3) not null,
  ETL_JOB    VARCHAR2(50) not null,
  ALLOW      CHAR(1),
  BEGINHOUR  NUMBER(38),
  ENDHOUR    NUMBER(38)
)
;

prompt Creating ETL_JOB_TRACE...
create table ETL_JOB_TRACE
(
  ETL_SYSTEM CHAR(3) not null,
  ETL_JOB    VARCHAR2(50) not null,
  TXDATE     DATE not null,
  JOBSTATUS  VARCHAR2(20),
  STARTTIME  CHAR(19),
  ENDTIME    CHAR(19)
)
;

prompt Creating ETL_NOTIFICATION...
create table ETL_NOTIFICATION
(
  ETL_SYSTEM     CHAR(3) not null,
  ETL_JOB        VARCHAR2(50) not null,
  SEQID          NUMBER(38) not null,
  DESTTYPE       CHAR(1),
  GROUPNAME      VARCHAR2(15),
  USERNAME       VARCHAR2(15),
  TIMING         CHAR(1),
  ATTACHLOG      CHAR(1),
  EMAIL          CHAR(1),
  SHORTMESSAGE   CHAR(1),
  MESSAGESUBJECT VARCHAR2(160),
  MESSAGECONTENT VARCHAR2(255)
)
;

prompt Creating ETL_RECEIVED_FILE...
create table ETL_RECEIVED_FILE
(
  ETL_SYSTEM     CHAR(3) not null,
  ETL_JOB        VARCHAR2(50) not null,
  JOBSESSIONID   NUMBER(38) not null,
  RECEIVEDFILE   VARCHAR2(50) not null,
  FILESIZE       NUMBER(18),
  EXPECTEDRECORD NUMBER(38),
  ARRIVALTIME    CHAR(19),
  RECEIVEDTIME   CHAR(19),
  LOCATION       VARCHAR2(128),
  STATUS         CHAR(1)
)
;

prompt Creating ETL_RECORD_LOG...
create table ETL_RECORD_LOG
(
  ETL_SYSTEM      CHAR(3) not null,
  ETL_JOB         VARCHAR2(50) not null,
  JOBSESSIONID    NUMBER(38) not null,
  RECORDTIME      CHAR(19),
  INSERTEDRECORD  NUMBER(38),
  UPDATEDRECORD   NUMBER(38),
  DELETEDRECORD   NUMBER(38),
  DUPLICATERECORD NUMBER(38),
  OUTPUTRECORD    NUMBER(38),
  ETRECORD        NUMBER(38),
  UVRECORD        NUMBER(38),
  ER1RECORD       NUMBER(38)
)
;

prompt Creating ETL_RELATEDJOB...
create table ETL_RELATEDJOB
(
  ETL_SYSTEM    CHAR(3) not null,
  ETL_JOB       VARCHAR2(50) not null,
  RELATEDSYSTEM CHAR(3) not null,
  RELATEDJOB    VARCHAR2(50) not null,
  CHECKMODE     CHAR(1),
  DESCRIPTION   VARCHAR2(50)
)
;

prompt Creating ETL_SERVER...
create table ETL_SERVER
(
  ETL_SERVER  VARCHAR2(10) not null,
  DESCRIPTION VARCHAR2(50),
  IPADDRESS   VARCHAR2(15),
  AGENTPORT   NUMBER(38),
  LIVECOUNT   NUMBER(38)
)
;

prompt Creating ETL_SYS...
create table ETL_SYS
(
  ETL_SYSTEM       CHAR(3) not null,
  DESCRIPTION      VARCHAR2(50),
  DATAKEEPPERIOD   NUMBER(38),
  LOGKEEPPERIOD    NUMBER(38),
  RECORDKEEPPERIOD NUMBER(38)
)
;

prompt Creating ETL_TABLE...
create table ETL_TABLE
(
  TABLENAME VARCHAR2(40),
  TABLEDESC VARCHAR2(60)
)
;

prompt Creating ETL_TIMETRIGGER...
create table ETL_TIMETRIGGER
(
  ETL_SYSTEM  CHAR(3) not null,
  ETL_JOB     VARCHAR2(50) not null,
  TRIGGERTYPE CHAR(1),
  STARTHOUR   NUMBER(38),
  STARTMIN    NUMBER(38),
  OFFSETDAY   NUMBER(38),
  LASTRUNDATE NUMBER(38),
  LASTRUNTIME NUMBER(38)
)
;

prompt Creating ETL_TIMETRIGGER_CALENDAR...
create table ETL_TIMETRIGGER_CALENDAR
(
  ETL_SYSTEM CHAR(3) not null,
  ETL_JOB    VARCHAR2(50) not null,
  SEQ        NUMBER(38) not null,
  YEARNUM    NUMBER(38),
  MONTHNUM   NUMBER(38),
  DAYNUM     NUMBER(38)
)
;

prompt Creating ETL_TIMETRIGGER_MONTHLY...
create table ETL_TIMETRIGGER_MONTHLY
(
  ETL_SYSTEM CHAR(3) not null,
  ETL_JOB    VARCHAR2(50) not null,
  TIMING     CHAR(31) not null,
  ENDOFMONTH CHAR(1) not null
)
;

prompt Creating ETL_TIMETRIGGER_WEEKLY...
create table ETL_TIMETRIGGER_WEEKLY
(
  ETL_SYSTEM CHAR(3) not null,
  ETL_JOB    VARCHAR2(50) not null,
  TIMING     CHAR(7) not null
)
;

prompt Creating ETL_UNLOAD_PRO...
create table ETL_UNLOAD_PRO
(
  DATA_SRC    VARCHAR2(3),
  DATA_GROUP  VARCHAR2(5),
  TASK_NAME   VARCHAR2(50),
  SRC_DDL     VARCHAR2(20),
  DDLDB       VARCHAR2(20),
  EXPORT_PATH VARCHAR2(50),
  FILE_NAME   VARCHAR2(50),
  PATH_FLG    VARCHAR2(1),
  ENCODING    VARCHAR2(20),
  DELIMITER   VARCHAR2(2),
  IS_COK      VARCHAR2(1),
  IS_WOK      VARCHAR2(1),
  IS_FULL     VARCHAR2(1)
)
;
comment on table ETL_UNLOAD_PRO
  is '???????????????';
comment on column ETL_UNLOAD_PRO.DATA_SRC
  is '????????????       ';
comment on column ETL_UNLOAD_PRO.DATA_GROUP
  is '???????????????      ';
comment on column ETL_UNLOAD_PRO.TASK_NAME
  is '????????????       ';
comment on column ETL_UNLOAD_PRO.SRC_DDL
  is '????????????DDL    ';
comment on column ETL_UNLOAD_PRO.DDLDB
  is '??????????????????DDL??? ';
comment on column ETL_UNLOAD_PRO.EXPORT_PATH
  is '??????????????????     ';
comment on column ETL_UNLOAD_PRO.FILE_NAME
  is '???????????????      ';
comment on column ETL_UNLOAD_PRO.PATH_FLG
  is '????????????       ';
comment on column ETL_UNLOAD_PRO.ENCODING
  is '????????????       ';
comment on column ETL_UNLOAD_PRO.DELIMITER
  is '?????????        ';
comment on column ETL_UNLOAD_PRO.IS_COK
  is '????????????OK??????   ';
comment on column ETL_UNLOAD_PRO.IS_WOK
  is '?????????OK??????????????????';
comment on column ETL_UNLOAD_PRO.IS_FULL
  is '???????????????';

prompt Creating ETL_USER...
create table ETL_USER
(
  USERNAME    VARCHAR2(15) not null,
  DESCRIPTION VARCHAR2(50),
  EMAIL       VARCHAR2(50),
  MOBILE      VARCHAR2(20),
  STATUS      CHAR(1)
)
;

prompt Creating ETL_USERGROUP...
create table ETL_USERGROUP
(
  GROUPNAME   VARCHAR2(15) not null,
  DESCRIPTION VARCHAR2(50)
)
;

prompt Loading CONTROL_LOGGER...
insert into CONTROL_LOGGER (TASK_NAME, SYS_NAME, STARTDATE, ENDDATE, MSG, ETLDATE, STATUS)
values ('S26_CUX_GL_BALANCES_T', 'S26', '2014-03-11 09:20:54' || chr(10) || '', '2014-03-11 09:20:54' || chr(10) || '', 'CUX_GL_BALANCES_T鏂囦欢鍖归厤姝ｇ‘', '2014-01-31', 1);
prompt 1 records loaded
prompt Loading CONTROL_TASK...
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSACCINACTIVEREG', 'S01', 'DPSACCINACTIVEREG', 'S01_DPSACCINACTIVEREG', '久悬未取户登记簿', 'DPSACCINACTIVEREG', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSACCLNKREG', 'S01', 'DPSACCLNKREG', 'S01_DPSACCLNKREG', '存款帐户关联登记表', 'DPSACCLNKREG', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSACCOUNTINFO', 'S01', 'DPSACCOUNTINFO', 'S01_DPSACCOUNTINFO', '存款静态表', 'DPSACCOUNTINFO', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSACCTFLOATRATE', 'S01', 'DPSACCTFLOATRATE', 'S01_DPSACCTFLOATRATE', '账户协议利率登记表', 'DPSACCTFLOATRATE', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSACCTLINK', 'S01', 'DPSACCTLINK', 'S01_DPSACCTLINK', '存款帐户关系表', 'DPSACCTLINK', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSACCTPRY', 'S01', 'DPSACCTPRY', 'S01_DPSACCTPRY', '帐户性质控制', 'DPSACCTPRY', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSAGREEMENT', 'S01', 'DPSAGREEMENT', 'S01_DPSAGREEMENT', '协定存款签约记录', 'DPSAGREEMENT', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSCALCINTLIST', 'S01', 'DPSCALCINTLIST', 'S01_DPSCALCINTLIST', '计息明细表', 'DPSCALCINTLIST', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSCALLNOTICE', 'S01', 'DPSCALLNOTICE', 'S01_DPSCALLNOTICE', '通知存款通知登记表', 'DPSCALLNOTICE', 0);
insert into CONTROL_TASK (TASK_NAME, SYS_NAME, SRC_TABLE, TGT_TABLE, TABLE_CN, FILE_NAME, STATUS)
values ('S01_DPSCHKBALREG', 'S01', 'DPSCHKBALREG', 'S01_DPSCHKBALREG', '客户余额对账函信息登记簿', 'DPSCHKBALREG', 0);
prompt 10 records loaded
prompt Loading CTL_TABLE_LOG...
prompt Table is empty
prompt Loading DATACALENDAR...
prompt Table is empty
prompt Loading DATACALENDARYEAR...
prompt Table is empty
prompt Loading D_ETLDATE...
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-01-31', null, null, 'U01', 1);
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-01-31', null, null, 'U02', 1);
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-01-31', null, null, 'M01', 1);
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-01-31', null, null, 'U05', 1);
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-02-01', null, null, 'CONTROL', 1);
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-01-31', null, null, 'SDSDATA', 1);
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-01-31', null, null, 'BDSDATA', 1);
insert into D_ETLDATE (ETLDATE, STARTDATE, ENDDATE, SYS_TYPE, STATUS)
values ('2014-01-31', null, null, 'ADSDATA', 1);
prompt 8 records loaded
prompt Loading ETL_DATA_SYSTEM...
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', 'S06', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', 'S15', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', '   ', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', 'S03', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', 'S10', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('汇总层', 'C01', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('汇总层', '   ', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', 'S07', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', 'tst', null);
insert into ETL_DATA_SYSTEM (ETL_DATA_SYSTEM, ETL_SYSTEM, ETL_SERVER)
values ('临时层', 'S02', null);
prompt 10 records loaded
prompt Loading ETL_EVENT...
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131121025319MAS2', 'O', 'L', '[SVI], [SVI_VIRTUAL] Dependent job [S01, S01_FGSOPEXDETAIL] does not finish yet, wait for next time!', '2013-11-21 02:53:19', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131122024813MAS2', 'O', 'L', '[T03], [T03_AGT_STATST_HIS] Dependent job [S05, S05_TBSHARE0] does not finish yet, wait for next time!', '2013-11-22 02:48:13', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131122025218MAS5', 'O', 'L', '[T03], [T03_AGT] Dependent job [S10, S10_TBL_CARD_INF] does not finish yet, wait for next time!', '2013-11-22 02:52:18', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131122025733MAS6', 'O', 'L', '[C04], [C04_FUND_DEPOSIT_DTL] Dependent job [T05, T05_GLSSUBTRANSLOG] does not finish yet, wait for next time!', '2013-11-22 02:57:33', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131120102930MAS4', 'O', 'L', '[C02], [C02_LOAN_CONTR_INFO] Dependent job [T01, T01_PARTY] does not finish yet, wait for next time!', '2013-11-20 10:29:30', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131120103247MAS8', 'O', 'L', '[C07], [C07_BANK_CARD_INFO] Dependent job [C01, C01_DEPOSIT_DAY_SUM] does not finish yet, wait for next time!', '2013-11-20 10:32:47', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131122025734MAS7', 'O', 'L', '[T03], [T03_AGT_INTR_HIS] Dependent job [S09, S09_V_LDREPODEALS_NEW] does not finish yet, wait for next time!', '2013-11-22 02:57:34', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131122030025MAS4', 'O', 'L', '[C01], [C01_CUST_DEPOSIT_DAY_SUM] Dependent job [C01, C01_REGULAR_DEPOSIT_PROPERTY] does not finish yet, wait for next time!', '2013-11-22 03:00:25', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131122030025MAS5', 'O', 'L', '[C01], [C01_ORG_DEPOSIT_DAY_SUM] Dependent job [C01, C01_REGULAR_DEPOSIT_PROPERTY] does not finish yet, wait for next time!', '2013-11-22 03:00:25', null);
insert into ETL_EVENT (EVENTID, EVENTSTATUS, SEVERITY, DESCRIPTION, LOGTIME, CLOSETIME)
values ('20131122030052MAS6', 'O', 'L', '[CVI], [CVI_VIRTUAL] Dependent job [C01, C01_CUST_DEPOSIT_DAY_SUM] does not finish yet, wait for next time!', '2013-11-22 03:00:52', null);
prompt 10 records loaded
prompt Loading ETL_GROUPMEMBER...
prompt Table is empty
prompt Loading ETL_IGN_BYPASS_JOBS...
prompt Table is empty
prompt Loading ETL_JOB...
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_ACCOUNTS_RECEIVABLE', 'ETL1', 'T10_ACCOUNTS_RECEIVABLE', '0', 'D', '1', '2013-12-09 02:52:37', '2013-12-09 02:52:52', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_accounts_receivable0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_ASSET_AGT_RELA_HIS', 'ETL1', 'T10_ASSET_AGT_RELA_HIS', '0', 'D', '1', '2013-12-09 02:55:39', '2013-12-09 02:56:09', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_asset_agt_rela_his0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_SEAS_USE_RIGHT', 'ETL1', 'T10_SEAS_USE_RIGHT', '0', 'D', '1', '2013-12-09 02:56:37', '2013-12-09 02:56:47', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_seas_use_right0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_LADING_BILL', 'ETL1', 'T10_LADING_BILL', '0', 'D', '1', '2013-12-09 03:02:10', '2013-12-09 03:02:40', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_lading_bill0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_BILL_ASSET', 'ETL1', 'T10_BILL_ASSET', '0', 'D', '1', '2013-12-09 02:50:53', '2013-12-09 02:51:17', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_bill_asset0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_CONSTRUCTION_PROJECT', 'ETL1', 'T10_CONSTRUCTION_PROJECT', '0', 'D', '1', '2013-12-09 03:01:54', '2013-12-09 03:02:43', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_construction_project0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_CIRCULATING_ASSET', 'ETL1', 'T10_CIRCULATING_ASSET', '0', 'D', '1', '2013-12-09 03:01:43', '2013-12-09 03:01:49', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_circulating_asset0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_CERT', 'ETL1', 'T10_CERT', '0', 'D', '1', '2013-12-09 02:55:39', '2013-12-09 02:56:01', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_cert0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_DEPOT_ITEM', 'ETL1', 'T10_DEPOT_ITEM', '0', 'D', '1', '2013-12-09 03:01:54', '2013-12-09 03:02:16', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_depot_item0200.pl', 4, 0, 'Y', null, null);
insert into ETL_JOB (ETL_SYSTEM, ETL_JOB, ETL_SERVER, DESCRIPTION, FREQUENCY, JOBTYPE, ENABLE, LAST_STARTTIME, LAST_ENDTIME, LAST_JOBSTATUS, LAST_TXDATE, LAST_FILECNT, LAST_CUBESTATUS, CUBEFLAG, CHECKFLAG, AUTOOFF, CHECKCALENDAR, CALENDARBU, RUNNINGSCRIPT, JOBSESSIONID, EXPECTEDRECORD, CHECKLASTSTATUS, TIMETRIGGER, JOB_PRIORITY)
values ('T10', 'T10_GUARANTEE', 'ETL1', 'T10_GUARANTEE', '0', 'D', '1', '2013-12-09 02:49:40', '2013-12-09 02:49:51', 'Done', to_date('05-02-2014', 'dd-mm-yyyy'), 0, null, 'N', 'Y', 'N', 'N', null, 't10_guarantee0200.pl', 4, 0, 'Y', null, null);
prompt 10 records loaded
prompt Loading ETL_JOB_DEPENDENCY...
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_BILL_COUNTERPART_INFO', 'S08', 'S08_CUST_INFO_MANG', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_CORP_PTY', 'S01', 'S01_CISCUSTOMERINFO', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_CORP_PTY', 'S01', 'S01_CISUNITINFO', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_COUNTERPART', 'S01', 'S01_CISCUSTOMERINFO', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_COUNTERPART', 'S01', 'S01_CISUNITINFO', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_INDIV_PTY', 'S01', 'S01_CISCUSTOMERINFO', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_INDIV_PTY', 'S01', 'S01_CISPERSONINFO', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_INDIV_PTY', 'S01', 'S01_CISPERSONSUPPLE', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_INDIV_PTY', 'S01', 'S01_CISEMPLOYMENT', null, '1');
insert into ETL_JOB_DEPENDENCY (ETL_SYSTEM, ETL_JOB, DEPENDENCY_SYSTEM, DEPENDENCY_JOB, DESCRIPTION, ENABLE)
values ('T01', 'T01_CORE_PTY_HIS', 'S01', 'S01_CISCUSTOMERINFO', null, '1');
prompt 10 records loaded
prompt Loading ETL_JOB_GROUP...
prompt Table is empty
prompt Loading ETL_JOB_GROUPCHILD...
prompt Table is empty
prompt Loading ETL_JOB_INI...
insert into ETL_JOB_INI (ETL_JOB)
values ('T01_CREDIT_USER_ORG_HIS');
insert into ETL_JOB_INI (ETL_JOB)
values ('T01_CREDIT_USER_POSITION_HIS');
insert into ETL_JOB_INI (ETL_JOB)
values ('T01_CREDIT_USER_BINDING_HIS');
prompt 3 records loaded
prompt Loading ETL_JOB_LOG...
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('U03', 'U03_S47_CORPORATION', 51, 'u03_s47_corporation0200.pl', to_date('25-01-2014', 'dd-mm-yyyy'), '2014-03-10 15:36:00', '2014-03-10 15:37:38', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('S26', 'S26_GL_CODE_COMBINATIONS', 6, 's26_gl_code_combinations0100.pl', to_date('31-12-2013', 'dd-mm-yyyy'), '2014-01-03 09:31:43', '2014-01-03 09:32:45', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('S26', 'S26_FND_FLEX_VALUE_SETS', 7, 's26_fnd_flex_value_sets0100.pl', to_date('01-01-2014', 'dd-mm-yyyy'), '2014-01-03 10:00:28', '2014-01-03 10:00:36', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('S26', 'S26_CUX_GL_OTHER_ACCOUNT_MAPPING', 7, 's26_cux_gl_other_account_mapping0100.pl', to_date('01-01-2014', 'dd-mm-yyyy'), '2014-01-03 10:00:38', '2014-01-03 10:00:41', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('S26', 'S26_CUX_GL_ORG_MAPPING', 8, 's26_cux_gl_org_mapping0100.pl', to_date('02-01-2014', 'dd-mm-yyyy'), '2014-01-03 10:19:05', '2014-01-03 10:19:08', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('S26', 'S26_FND_FLEX_VALUE_SETS', 41, 's26_fnd_flex_value_sets0100.pl', to_date('25-01-2014', 'dd-mm-yyyy'), '2014-02-07 10:14:20', '2014-02-07 10:14:28', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('U03', 'U03_S45_EBANK_CTL_EXP', 3, 'u03_s45_ebank_ctl_exp0300.pl', to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:07:26', '2014-02-19 10:08:46', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('U03', 'U03_S87_TX_CD', 2, 'u03_s87_tx_cd0200.pl', to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:12:23', '2014-02-19 10:12:55', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('U03', 'U03_TEMP_TRANSLOG', 8, 'u03_temp_translog0200.pl', to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:13:37', '2014-02-19 10:20:19', 0, null);
insert into ETL_JOB_LOG (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, SCRIPTFILE, TXDATE, STARTTIME, ENDTIME, RETURNCODE, SECONDS)
values ('U03', 'U03_S47_CP_DEPOSIT', 1, 'u03_s47_cp_deposit0200.pl', to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:25:07', '2014-02-19 10:27:07', 0, null);
prompt 10 records loaded
prompt Loading ETL_JOB_QUEUE...
prompt Table is empty
prompt Loading ETL_JOB_SOURCE...
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_export_negotiation_his', 'T03', 'T03_EXPORT_NEGOTIATION_HIS', 'T03_EXPORT_NEGOTIATION_HIS', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_dep_sleep_acct', 'T03', 'T03_DEP_SLEEP_ACCT', 'T03_DEP_SLEEP_ACCT', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_dep_acct', 'T03', 'T03_DEP_ACCT', 'T03_DEP_ACCT', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_loan_acct_dtl_his', 'T03', 'T03_LOAN_ACCT_DTL_HIS', 'T03_LOAN_ACCT_DTL_HIS', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_guar_contr_his', 'T03', 'T03_GUAR_CONTR_HIS', 'T03_GUAR_CONTR_HIS', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_fix_dep_his', 'T03', 'T03_FIX_DEP_HIS', 'T03_FIX_DEP_HIS', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_appl_lmt_his', 'T03', 'T03_APPL_LMT_HIS', 'T03_APPL_LMT_HIS', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_clean_collection_his', 'T03', 'T03_CLEAN_COLLECTION_HIS', 'T03_CLEAN_COLLECTION_HIS', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_contr_acct', 'T03', 'T03_CONTR_ACCT', 'T03_CONTR_ACCT', '0', '0', 0, 0, 0, 9);
insert into ETL_JOB_SOURCE (SOURCE, ETL_SYSTEM, ETL_JOB, CONV_FILE_HEAD, AUTOFILTER, ALERT, BEFOREHOUR, BEFOREMIN, OFFSETDAY, LASTCOUNT)
values ('t03_cur_dep_his', 'T03', 'T03_CUR_DEP_HIS', 'T03_CUR_DEP_HIS', '0', '0', 0, 0, 0, 9);
prompt 10 records loaded
prompt Loading ETL_JOB_STATUS...
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U04', 'U04_GRXDFHZ', 0, to_date('31-01-2014', 'dd-mm-yyyy'), '2014-02-12 16:45:55', '2014-02-12 16:46:27', 'Done', null, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U03', 'U03_S45_EBANK_CTL_EXP', 3, to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:07:26', '2014-02-19 10:08:46', 'Done', 0, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U03', 'U03_S87_TX_CD', 2, to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:12:23', '2014-02-19 10:12:55', 'Done', 0, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U04', 'U04_DGHQCKFHZMXJL', 0, to_date('31-01-2014', 'dd-mm-yyyy'), '2014-02-12 16:46:27', '2014-02-12 16:47:40', 'Done', null, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U04', 'U04_XYKXX', 0, to_date('31-01-2014', 'dd-mm-yyyy'), '2014-02-12 16:48:33', '2014-02-12 16:48:56', 'Done', null, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('S01', 'S01_DPSACCTPRY', 157, to_date('01-02-2014', 'dd-mm-yyyy'), '2014-02-13 09:24:32', '2014-02-13 09:24:38', 'Done', 1, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U03', 'U03_TEMP_TRANSLOG', 8, to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:13:37', '2014-02-19 10:20:19', 'Done', 0, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U03', 'U03_S47_CP_DEPOSIT', 1, to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:25:07', '2014-02-19 10:27:07', 'Done', 0, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U03', 'U03_S47_CP_DEPOSIT_EXP', 2, to_date('30-11-2013', 'dd-mm-yyyy'), '2014-02-19 10:27:08', '2014-02-19 10:27:34', 'Done', 0, null, 0);
insert into ETL_JOB_STATUS (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, TXDATE, STARTTIME, ENDTIME, JOBSTATUS, FILECNT, CUBESTATUS, EXPECTEDRECORD)
values ('U04', 'U04_GRDQCKFHZMXJL', 11, to_date('20-09-2013', 'dd-mm-yyyy'), '2014-02-19 11:17:51', '2014-02-19 12:07:58', 'Done', 0, null, 0);
prompt 10 records loaded
prompt Loading ETL_JOB_STREAM...
insert into ETL_JOB_STREAM (ETL_SYSTEM, ETL_JOB, STREAM_SYSTEM, STREAM_JOB, DESCRIPTION, ENABLE)
values ('C01', 'C01_DEPOSIT_DAY_SUM', 'R01', 'R01_CUST_INDIV_D_SUM', null, '1');
insert into ETL_JOB_STREAM (ETL_SYSTEM, ETL_JOB, STREAM_SYSTEM, STREAM_JOB, DESCRIPTION, ENABLE)
values ('R01', 'R01_CUST_INDIV_D_SUM', 'U06', 'U06_CUST_INDIV_D_SUM', null, '1');
prompt 2 records loaded
prompt Loading ETL_JOB_TIMEWINDOW...
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_LNSGUARANTLIST', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_LNSISSUEREG', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_LNSRATELIST', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_LNSREDISCONLIST', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_LNSREPAYADJUST', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_LNSRPYLIST', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_LNSWRTOFFREG', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_MBFECHECKREG', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_MBFEFREEINFOREG', 'Y', 0, 23);
insert into ETL_JOB_TIMEWINDOW (ETL_SYSTEM, ETL_JOB, ALLOW, BEGINHOUR, ENDHOUR)
values ('T05', 'T05_MBFEQUERYREG', 'Y', 0, 23);
prompt 10 records loaded
prompt Loading ETL_JOB_TRACE...
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('24-12-2013', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('27-12-2013', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('03-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('08-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('09-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('10-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('12-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('13-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('16-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
insert into ETL_JOB_TRACE (ETL_SYSTEM, ETL_JOB, TXDATE, JOBSTATUS, STARTTIME, ENDTIME)
values ('U07', 'U07_TM_DS_STDARMSEC', to_date('27-01-2014', 'dd-mm-yyyy'), 'Waiting', null, null);
prompt 10 records loaded
prompt Loading ETL_NOTIFICATION...
prompt Table is empty
prompt Loading ETL_RECEIVED_FILE...
insert into ETL_RECEIVED_FILE (ETL_SYSTEM, ETL_JOB, JOBSESSIONID, RECEIVEDFILE, FILESIZE, EXPECTEDRECORD, ARRIVALTIME, RECEIVEDTIME, LOCATION, STATUS)
values ('S26', 'S26_CUX_GL_BALANCES_T', 80, 'S26_S26_CUX_GL_BALANCES_T_20140131.lst', 51, 0, '2014-03-11 15:03:52', '2014-03-11 09:20:58', '/EDW/ETL/INSTANCE/ETL1/DATA/complete/S26/20140311', '1');
prompt 1 records loaded
prompt Loading ETL_RECORD_LOG...
prompt Table is empty
prompt Loading ETL_RELATEDJOB...
prompt Table is empty
prompt Loading ETL_SERVER...
insert into ETL_SERVER (ETL_SERVER, DESCRIPTION, IPADDRESS, AGENTPORT, LIVECOUNT)
values ('ETL1', null, '31.2.2.55', 6346, 0);
insert into ETL_SERVER (ETL_SERVER, DESCRIPTION, IPADDRESS, AGENTPORT, LIVECOUNT)
values ('ETL2', null, '31.2.2.55', 6347, 444717);
prompt 2 records loaded
prompt Loading ETL_SYS...
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('S08', '票据系统', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('S07', '农信银', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('C07', '银行卡主题', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('S05', '理财系统', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('C05', '财务主题', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('T03', '协议主题', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('T10', '资产主题', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('S01', '核心系统', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('C01', '存款主题', 30, 30, 30);
insert into ETL_SYS (ETL_SYSTEM, DESCRIPTION, DATAKEEPPERIOD, LOGKEEPPERIOD, RECORDKEEPPERIOD)
values ('S10', 'IC卡系统', 30, 30, 30);
prompt 10 records loaded
prompt Loading ETL_TABLE...
prompt Table is empty
prompt Loading ETL_TIMETRIGGER...
prompt Table is empty
prompt Loading ETL_TIMETRIGGER_CALENDAR...
prompt Table is empty
prompt Loading ETL_TIMETRIGGER_MONTHLY...
prompt Table is empty
prompt Loading ETL_TIMETRIGGER_WEEKLY...
prompt Table is empty
prompt Loading ETL_UNLOAD_PRO...
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_CISCUSTACCINFO', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_ciscustaccinfo.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_CISCUSTOMERINFO', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_ciscustomerinfo.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_CMSCARDINFO', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_cmscardinfo.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_V01_DMSVOUSALEREG', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_dmsvousalereg.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_DMSVOUUSEDREG', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_dmsvouusedreg.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_DPSACCOUNTINFO', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_dpsaccountinfo.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_DPSACCTLINK', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_dpsacctlink.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_DPSACCTPRY', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_dpsacctpry.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_DPSFREEZEREG', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_dpsfreezereg.txt', '0', 'GB18030', '|', '0', '0', null);
insert into ETL_UNLOAD_PRO (DATA_SRC, DATA_GROUP, TASK_NAME, SRC_DDL, DDLDB, EXPORT_PATH, FILE_NAME, PATH_FLG, ENCODING, DELIMITER, IS_COK, IS_WOK, IS_FULL)
values ('U02', 'S01', 'U02_S01_DPSOPENCLOSEACCREG', 'SDSDATA', 'USDSDDL', 'SHJD/hexin', 'ods_dpsopencloseaccreg.txt', '0', 'GB18030', '|', '0', '0', null);
prompt 10 records loaded
prompt Loading ETL_USER...
prompt Table is empty
prompt Loading ETL_USERGROUP...
prompt Table is empty
set feedback on
set define on
prompt Done.
