
CREATE MULTISET TABLE DataCalendar ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      CalendarYear INTEGER NOT NULL,
      SeqNum INTEGER NOT NULL,
      CalendarMonth INTEGER NOT NULL,
      CalendarDay INTEGER NOT NULL,
      CheckFlag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX XPKDataCalendar ( ETL_System ,ETL_Job ,CalendarYear ,
SeqNum );

CREATE MULTISET TABLE DataCalendarYear ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      CalendarYear INTEGER NOT NULL)
UNIQUE PRIMARY INDEX XPKDataCalendarYear ( ETL_System ,ETL_Job ,
CalendarYear );

CREATE MULTISET TABLE ETL_Backup_Log ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      Backup_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'BACKUP Job Name' NOT NULL,
      JobID INTEGER TITLE 'Job ID' NOT NULL,
      InstanceID INTEGER TITLE 'Job Instance ID' NOT NULL,
      TXDate DATE FORMAT 'YYYYMMDD' NOT NULL,
      ReturnCode INTEGER,
      start_date CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      end_date CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      sys_time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6))
PRIMARY INDEX ( Backup_Job ,JobID ,InstanceID );

CREATE MULTISET TABLE ETL_Event ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      EventID VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Event ID' NOT NULL,
      EventStatus CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Event Status' NOT NULL,
      Severity CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Event Severity' NOT NULL,
      Description VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Event Description',
      LogTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Log Time' NOT NULL,
      CloseTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Close Time')
UNIQUE PRIMARY INDEX XPKETL_Event ( EventID );

CREATE MULTISET TABLE ETL_GroupMember ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      UserName VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'User Name' NOT NULL,
      GroupName VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'User Group Name' NOT NULL)
UNIQUE PRIMARY INDEX XPKETL_GroupMember ( UserName ,GroupName );

CREATE MULTISET TABLE etl_ign_bypass_jobs ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      etl_system CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'etl system name' NOT NULL,
      etl_job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'etl job name' NOT NULL)
UNIQUE PRIMARY INDEX xak1etl_job ( etl_system ,etl_job );

CREATE MULTISET TABLE ETL_Job ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      ETL_Server VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Server Name',
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Frequency VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      JobType CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      Enable CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      Last_StartTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      Last_EndTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      Last_JobStatus VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      Last_TXDate DATE FORMAT 'YYYY-MM-DD',
      Last_FileCnt INTEGER,
      Last_CubeStatus CHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      CubeFlag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Last_CubeFlag',
      CheckFlag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      AutoOff CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      CheckCalendar CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      CalendarBU VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC,
      RunningScript VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Running Script Name',
      JobSessionID INTEGER TITLE 'Job Session ID',
      ExpectedRecord INTEGER TITLE 'Expected Record',
      CheckLastStatus CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Check Last Time Status',
      TimeTrigger CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Time Trigger',
      Job_Priority smallint default 30 Title 'Priority')
UNIQUE PRIMARY INDEX XAK1ETL_Job ( ETL_System ,ETL_Job );

CREATE MULTISET TABLE ETL_Job_Dependency ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      Dependency_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dependency System Name' NOT NULL,
      Dependency_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Dependency Job Name' NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Enable CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX XIE1ETL_Job_Dependency ( ETL_System ,ETL_Job )
UNIQUE INDEX XAK1ETL_Job_Dependency ( ETL_System ,ETL_Job ,Dependency_System ,
Dependency_Job );

CREATE MULTISET TABLE ETL_Job_Group ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      GroupName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Head System Name',
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Head Job Name',
      AutoOnChild CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX XAK1ETL_Job_Group ( GroupName );

CREATE MULTISET TABLE ETL_Job_GroupChild ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      GroupName VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Child System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Child Job Name' NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Enable CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      CheckFlag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      TxDate CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      TurnOnFlag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX XAK1ETL_Job_GroupChild ( GroupName ,ETL_System ,
ETL_Job );

CREATE MULTISET TABLE ETL_Job_Log ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      JobSessionID INTEGER TITLE 'Job Session ID' NOT NULL,
      ScriptFile VARCHAR(60) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      TXDate DATE FORMAT 'YY/MM/DD' NOT NULL,
      StartTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      EndTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      ReturnCode INTEGER,
      Seconds INTEGER)
UNIQUE PRIMARY INDEX XAK1ETL_Job_Log ( ETL_System ,ETL_Job ,JobSessionID ,
ScriptFile );

CREATE MULTISET TABLE ETL_Job_Queue ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_Server VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Server' NOT NULL,
      SeqID INTEGER NOT NULL,
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      TXDate DATE FORMAT 'YYYY-MM-DD',
      RequestTime VARCHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Request Time')
UNIQUE PRIMARY INDEX XAK1ETL_Job_Queue ( ETL_Server ,SeqID );

CREATE MULTISET TABLE ETL_Job_Source ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      Source VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      Conv_File_Head VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Convert File Header' NOT NULL,
      AutoFilter CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Filter Out Duplicate File',
      Alert CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Alert When Missing',
      BeforeHour INTEGER TITLE 'Before Hour',
      BeforeMin INTEGER TITLE 'Before Min',
      OffsetDay INTEGER TITLE 'Offset Day',
      LastCount INTEGER TITLE 'Last Count')
UNIQUE PRIMARY INDEX XAK1ETL_Job_Source ( Source )
UNIQUE INDEX XAK2ETL_Job_Source ( ETL_System ,Conv_File_Head );

CREATE MULTISET TABLE ETL_Job_Status ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      JobSessionID INTEGER TITLE 'Job Session ID' NOT NULL,
      TXDate DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      StartTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      EndTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      JobStatus VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      FileCnt INTEGER,
      CubeStatus VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      ExpectedRecord INTEGER TITLE 'Expected Record')
UNIQUE PRIMARY INDEX XAK1ETL_Job_Status ( ETL_System ,ETL_Job ,
JobSessionID );

CREATE MULTISET TABLE ETL_Job_Stream ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      Stream_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Down Stream System Name' NOT NULL,
      Stream_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Down Stream Job Name' NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Enable CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX XIE1ETL_Job_Stream ( ETL_System ,ETL_Job )
UNIQUE INDEX XAK1ETL_Job_Stream ( ETL_System ,ETL_Job ,Stream_System ,
Stream_Job );

CREATE MULTISET TABLE ETL_Job_TimeWindow ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      Allow CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      BeginHour INTEGER,
      EndHour INTEGER)
UNIQUE PRIMARY INDEX XPKETL_Job_TimeWindow ( ETL_System ,ETL_Job );

CREATE MULTISET TABLE ETL_Job_Trace ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      TXDate DATE FORMAT 'YY/MM/DD' NOT NULL,
      JobStatus VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Job Status',
      StartTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Start Time',
      EndTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'End Time')
UNIQUE PRIMARY INDEX XPKETL_Job_Trace ( ETL_System ,ETL_Job ,
TXDate );

CREATE MULTISET TABLE ETL_Notification ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      SeqID INTEGER TITLE 'Sequence ID' NOT NULL,
      DestType CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Destination Type',
      GroupName VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'User Group Name',
      UserName VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'User Name',
      Timing CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      AttachLog CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      Email CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Through Email',
      ShortMessage CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Through Short Message',
      MessageSubject VARCHAR(160) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Message Subject',
      MessageContent VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Message Content')
UNIQUE PRIMARY INDEX XAK1ETL_Notification ( ETL_System ,ETL_Job ,
SeqID );

CREATE MULTISET TABLE ETL_Received_File ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      JobSessionID INTEGER TITLE 'Job Session ID' NOT NULL,
      ReceivedFile VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Received File Name' NOT NULL,
      FileSize DECIMAL(18,0) TITLE 'File Size',
      ExpectedRecord INTEGER TITLE 'Expected Record',
      ArrivalTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Arrival Time',
      ReceivedTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Received Time',
      Location VARCHAR(128) CHARACTER SET LATIN NOT CASESPECIFIC,
      Status CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX XAK1ETL_Received_File ( ETL_System ,ETL_Job ,
ReceivedFile );

CREATE MULTISET TABLE ETL_Record_Log ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      JobSessionID INTEGER TITLE 'Job Session ID' NOT NULL,
      RecordTime CHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC,
      InsertedRecord INTEGER TITLE 'Inserted Record',
      UpdatedRecord INTEGER TITLE 'Updated Record',
      DeletedRecord INTEGER TITLE 'Deleted Record',
      DuplicateRecord INTEGER TITLE 'Duplicate Record',
      OutputRecord INTEGER TITLE 'Output Record',
      ETRecord INTEGER TITLE 'ET Record',
      UVRecord INTEGER TITLE 'UV Record',
      ER1Record INTEGER TITLE 'ER1 Record',
      ER2Record INTEGER TITLE 'ER2 Record')
UNIQUE PRIMARY INDEX XAK1ETL_Record_Log ( ETL_System ,ETL_Job ,
JobSessionID );

CREATE MULTISET TABLE ETL_RelatedJob ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      RelatedSystem CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Related Job System' NOT NULL,
      RelatedJob VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Related Job Name' NOT NULL,
      CheckMode CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Checking Mode',
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX XPKETL_RelatedJob ( ETL_System ,ETL_Job ,
RelatedSystem ,RelatedJob );

CREATE MULTISET TABLE ETL_Server ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_Server VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Server Name' NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      IPAddress VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'IP Address',
      AgentPort INTEGER TITLE 'Agent Port',
      LiveCount INTEGER)
UNIQUE PRIMARY INDEX XPKETL_Server ( ETL_Server );

CREATE MULTISET TABLE ETL_Sys ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      DataKeepPeriod INTEGER TITLE 'Data Keep Period',
      LogKeepPeriod INTEGER TITLE 'Log File Keep Period',
      RecordKeepPeriod INTEGER TITLE 'Record Keep Period')
UNIQUE PRIMARY INDEX XAK1ETL_Sys ( ETL_System );

CREATE MULTISET TABLE ETL_TABLE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      tablename VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      tabledesc VARCHAR(60) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX ( tablename ,tabledesc );

CREATE MULTISET TABLE ETL_TimeTrigger ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      TriggerType CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Trigger Type',
      StartHour INTEGER TITLE 'Start Hour',
      StartMin INTEGER TITLE 'Start Min',
      OffsetDay INTEGER TITLE 'Offset Day',
      LastRunDate INTEGER TITLE 'Last Run Date',
      LastRunTime INTEGER TITLE 'Last Run Time')
UNIQUE PRIMARY INDEX XPKETL_TimeTrigger ( ETL_System ,ETL_Job );

CREATE MULTISET TABLE ETL_TimeTrigger_Calendar ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      Seq INTEGER NOT NULL,
      YearNum INTEGER TITLE 'Year',
      MonthNum INTEGER TITLE 'Month',
      DayNum INTEGER TITLE 'Day')
UNIQUE PRIMARY INDEX XPKETL_TimeTrigger_Calendar ( ETL_System ,
ETL_Job ,Seq );

CREATE MULTISET TABLE ETL_TimeTrigger_Monthly ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      Timing CHAR(31) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      EndOfMonth CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'End Of Month' NOT NULL)
UNIQUE PRIMARY INDEX XPKETL_TimeTrigger_Monthly ( ETL_System ,
ETL_Job );

CREATE MULTISET TABLE ETL_TimeTrigger_Weekly ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      ETL_System CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL System Name' NOT NULL,
      ETL_Job VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'ETL Job Name' NOT NULL,
      Timing CHAR(7) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL)
UNIQUE PRIMARY INDEX XPKETL_TimeTrigger_Weekly ( ETL_System ,
ETL_Job );

CREATE MULTISET TABLE ETL_User ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      UserName VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'User Name' NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Email VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Email Address',
      Mobile VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'Mobile Number',
      Status CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'User Status')
UNIQUE PRIMARY INDEX XAK1ETL_User ( UserName );

CREATE MULTISET TABLE ETL_UserGroup ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL
     (
      GroupName VARCHAR(15) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'User Group Name' NOT NULL,
      Description VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX XPKETL_UserGroup ( GroupName );

